<a href="https://colab.research.google.com/github/amitnits2016/fastai/blob/master/PyTorch/PyTorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch.__version__

'1.5.1+cu101'

In [2]:
x = torch.Tensor([5, 3])
y = torch.Tensor([2, 1])
print(x*y)

tensor([10.,  3.])


In [3]:
x = torch.zeros([2, 5])
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [4]:
x.shape

torch.Size([2, 5])

In [5]:
y = torch.rand([2, 5])
y

tensor([[0.5084, 0.3825, 0.6885, 0.9610, 0.9747],
        [0.9348, 0.1387, 0.1403, 0.5156, 0.9436]])

In [6]:
y.view([1, 10])

tensor([[0.5084, 0.3825, 0.6885, 0.9610, 0.9747, 0.9348, 0.1387, 0.1403, 0.5156,
         0.9436]])

In [7]:
y

tensor([[0.5084, 0.3825, 0.6885, 0.9610, 0.9747],
        [0.9348, 0.1387, 0.1403, 0.5156, 0.9436]])

In [8]:
y = y.view([1, 10])

In [9]:
y

tensor([[0.5084, 0.3825, 0.6885, 0.9610, 0.9747, 0.9348, 0.1387, 0.1403, 0.5156,
         0.9436]])